### ISSUE TITLE
-column -1 behavior

### ISSUE THREAD

**Issue by drq883** [coteditor/cot#10]
I use coteditor as an editor for a work journal script I wrote. When I start my script, I want the cursor be at the very end of the document. It is, but the cursor is in front of the last character.

Is there any way (or other value) you -column could support positioning the cursor after the last character?

**Comment by drq883** [comment]
I use coteditor as an editor for a work journal script I wrote. When I start my script, I want the cursor be at the very end of the document. It is, but the cursor is in front of the last character.

Is there any way (or other value) you -column could support positioning the cursor after the last character?

**Comment by 1024jp** [comment]
Humm, that's strange. Please tell me the versions of your:

- macOS
- CotEditor
- cot command (you can check it with `cot -v`)

FYI, the latest versions are 3.6.11 for CotEditor and 2.7.3 for `cot` command.

**Comment by drq883** [comment]
I tested this on my MacBook and it behaves as normal. This was on my MacPro yesterday. I'm away from the office.

On the MacBook, the versions are:

macOS: Mojave 10.14.1 (18B75)
CotEditor: Version 3.6.11 (309)
cot command: 2.7.3

Since things work as they should on the MacBook, there is nothing to do here. Feel free to close the issue. I obviously have something wrong on the MacPro.

**Comment by 1024jp** [comment]
Thank you for the additional info.

I found a specific condition in the current CotEditor 3.6.11/cot 2.7.3 that the insertion point is not put at the end of the line when `--column -1` is set.
Thus, when the document does not end with an empty new line. I'll fix this in the next CotEditor 3.6.12.

Besides, if you find any other conditions for this, please feel free to report them.
