### ISSUE TITLE
Create new file from command line without needing -n/--new, please

### ISSUE THREAD

**Issue by matthewsht** [coteditor/cot#19]
I searched back issues and found both #1 and #3 

I'd like to re-request this feature - from emacs to nano, vi to vscode, cot is the ONLY editor I know of that requires a command line flag to create a new file. Coming from... anything else, this is jarring.

The behavior would simply be to have cot do whatever it does for --new for any file that doesn't already exist.

(Other than this one small mis-feature (and it IS small) cot REALLY hits the sweet spot for a good basic editor - Thank You)

**Comment by 1024jp** [comment]
As I mentioned in https://github.com/coteditor/CotEditor/issues/1776, I take this request over to https://github.com/coteditor/CotEditor/issues/1776.
